# Generated by Django 5.2.16 on 2026-07-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('token_number', models.CharField(help_text='e.g., A-001, B-042', max_length=20, verbose_name='Token Number')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('ON_HOLD', 'On Hold')], default='WAITING', max_length=15)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Queue Position')),
                ('queue_date', models.DateField(verbose_name='Queue Date')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked At')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Called At')),
                ('serving_at', models.DateTimeField(blank=True, null=True, verbose_name='Serving At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0, verbose_name='Estimated Wait (min)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('booking_type', models.CharField(choices=[('ONLINE', 'Online Booking'), ('WALK_IN', 'Walk-in'), ('KIOSK', 'Kiosk')], default='ONLINE', max_length=10)),
                ('is_priority', models.BooleanField(default=False, verbose_name='Priority')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='branches.branch')),
                ('called_by', models.ForeignKey(blank=True, help_text='Staff member who called this token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_tokens', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='branches.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Queue Token',
                'verbose_name_plural': 'Queue Tokens',
                'ordering': ['queue_date', 'position'],
            },
        ),
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped'), ('ON_HOLD', 'Put On Hold'), ('RECALLED', 'Recalled')], max_length=15)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_actions', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='queues.queuetoken')),
            ],
            options={
                'verbose_name': 'Queue History',
                'verbose_name_plural': 'Queue History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['queue_date', 'status'], name='queues_queu_queue_d_833a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['branch', 'queue_date'], name='queues_queu_branch__e2b75d_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['user', 'queue_date'], name='queues_queu_user_id_9ea094_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queuetoken',
            unique_together={('token_number', 'queue_date', 'branch')},
        ),
    ]
