# Generated by Django 5.2.16 on 2026-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_queuetoken_counter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetoken',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='priority_weight',
            field=models.PositiveIntegerField(default=10, verbose_name='Priority Weight'),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='triage_level',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency Triage'), ('VIP', 'VIP Premium'), ('ELDERLY_DISABLED', 'Elderly / Differently Abled'), ('PRIORITY', 'Priority'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Code for self-service kiosk check-in', max_length=10, null=True, verbose_name='Verification Code'),
        ),
        migrations.AlterField(
            model_name='queuehistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped'), ('ON_HOLD', 'Put On Hold'), ('RECALLED', 'Recalled'), ('TRANSFERRED', 'Transferred')], max_length=15),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('ON_HOLD', 'On Hold'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=15),
        ),
    ]
