# Generated by Django 5.2.16 on 2026-07-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(max_length=200, verbose_name='Branch Name')),
                ('code', models.CharField(help_text='Unique code for the branch (e.g., CMB-GH)', max_length=20, unique=True, verbose_name='Branch Code')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('operating_hours', models.CharField(default='8:00 AM - 4:00 PM', help_text='e.g., 8:00 AM - 4:00 PM', max_length=100, verbose_name='Operating Hours')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='Branch Image')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(max_length=200, verbose_name='Department Name')),
                ('code', models.CharField(max_length=20, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('code', models.CharField(max_length=20, verbose_name='Service Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prefix', models.CharField(help_text='Prefix for queue tokens (e.g., A, B, C)', max_length=5, verbose_name='Token Prefix')),
                ('avg_service_time_minutes', models.PositiveIntegerField(default=10, help_text='Average time to serve one customer in minutes', verbose_name='Avg Service Time (min)')),
                ('max_daily_tokens', models.PositiveIntegerField(default=100, help_text='Maximum tokens that can be issued per day', verbose_name='Max Daily Tokens')),
                ('current_token_number', models.PositiveIntegerField(default=0, verbose_name='Current Token Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='branches.department')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
                'unique_together': {('department', 'code')},
            },
        ),
    ]
