# Generated by Django 5.2.16 on 2026-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='gateway_response_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gateway Response ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App'), ('WHATSAPP', 'WhatsApp'), ('SMS_GATEWAY', 'SMS Gateway')], default='IN_APP', max_length=15),
        ),
    ]
